// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpNzU1ibwTTn8nTqOUNkSbAqiHVAvKZM',
    appId: '1:1031271555902:web:917f26aba2cd3805ed826f',
    messagingSenderId: '1031271555902',
    projectId: 'cook-206ec',
    authDomain: 'cook-206ec.firebaseapp.com',
    storageBucket: 'cook-206ec.appspot.com',
    measurementId: 'G-QYXF629CWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gn97XNzqMWr1zqiRt7vwS4kYo3Q2904',
    appId: '1:1031271555902:android:36deeb2c2dc0ec92ed826f',
    messagingSenderId: '1031271555902',
    projectId: 'cook-206ec',
    storageBucket: 'cook-206ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlKkfbPwvH6gXMpn4LUNFV1l5tWgvGqw',
    appId: '1:1031271555902:ios:60c8200ee901524bed826f',
    messagingSenderId: '1031271555902',
    projectId: 'cook-206ec',
    storageBucket: 'cook-206ec.appspot.com',
    iosBundleId: 'com.example.cook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlKkfbPwvH6gXMpn4LUNFV1l5tWgvGqw',
    appId: '1:1031271555902:ios:3496dc592874c094ed826f',
    messagingSenderId: '1031271555902',
    projectId: 'cook-206ec',
    storageBucket: 'cook-206ec.appspot.com',
    iosBundleId: 'com.example.cook.RunnerTests',
  );
}
